export interface Country {
  code: string;
  name: string;
  currency: string;
  symbol: string;
  locale: string;
}

export function getFlagUrl(code: string): string {
  return `https://flagcdn.com/w40/${code.toLowerCase()}.png`;
}

export const COUNTRIES: Country[] = [
  // Asia
  { code: "AF", name: "Afghanistan", currency: "AFN", symbol: "؋", locale: "fa-AF" },
  { code: "AM", name: "Armenia", currency: "AMD", symbol: "֏", locale: "hy-AM" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", symbol: "₼", locale: "az-AZ" },
  { code: "BH", name: "Bahrain", currency: "BHD", symbol: ".د.ب", locale: "ar-BH" },
  { code: "BD", name: "Bangladesh", currency: "BDT", symbol: "৳", locale: "bn-BD" },
  { code: "BT", name: "Bhutan", currency: "BTN", symbol: "Nu.", locale: "dz-BT" },
  { code: "BN", name: "Brunei", currency: "BND", symbol: "B$", locale: "ms-BN" },
  { code: "KH", name: "Cambodia", currency: "KHR", symbol: "៛", locale: "km-KH" },
  { code: "CN", name: "China", currency: "CNY", symbol: "¥", locale: "zh-CN" },
  { code: "CY", name: "Cyprus", currency: "EUR", symbol: "€", locale: "el-CY" },
  { code: "GE", name: "Georgia", currency: "GEL", symbol: "₾", locale: "ka-GE" },
  { code: "IN", name: "India", currency: "INR", symbol: "₹", locale: "en-IN" },
  { code: "ID", name: "Indonesia", currency: "IDR", symbol: "Rp", locale: "id-ID" },
  { code: "IR", name: "Iran", currency: "IRR", symbol: "﷼", locale: "fa-IR" },
  { code: "IQ", name: "Iraq", currency: "IQD", symbol: "ع.د", locale: "ar-IQ" },
  { code: "IL", name: "Israel", currency: "ILS", symbol: "₪", locale: "he-IL" },
  { code: "JP", name: "Japan", currency: "JPY", symbol: "¥", locale: "ja-JP" },
  { code: "JO", name: "Jordan", currency: "JOD", symbol: "د.ا", locale: "ar-JO" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", symbol: "₸", locale: "kk-KZ" },
  { code: "KW", name: "Kuwait", currency: "KWD", symbol: "د.ك", locale: "ar-KW" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", symbol: "с", locale: "ky-KG" },
  { code: "LA", name: "Laos", currency: "LAK", symbol: "₭", locale: "lo-LA" },
  { code: "LB", name: "Lebanon", currency: "LBP", symbol: "ل.ل", locale: "ar-LB" },
  { code: "MY", name: "Malaysia", currency: "MYR", symbol: "RM", locale: "ms-MY" },
  { code: "MV", name: "Maldives", currency: "MVR", symbol: "Rf", locale: "dv-MV" },
  { code: "MN", name: "Mongolia", currency: "MNT", symbol: "₮", locale: "mn-MN" },
  { code: "MM", name: "Myanmar", currency: "MMK", symbol: "K", locale: "my-MM" },
  { code: "NP", name: "Nepal", currency: "NPR", symbol: "Rs.", locale: "ne-NP" },
  { code: "KP", name: "North Korea", currency: "KPW", symbol: "₩", locale: "ko-KP" },
  { code: "OM", name: "Oman", currency: "OMR", symbol: "﷼", locale: "ar-OM" },
  { code: "PK", name: "Pakistan", currency: "PKR", symbol: "Rs.", locale: "ur-PK" },
  { code: "PS", name: "Palestine", currency: "ILS", symbol: "₪", locale: "ar-PS" },
  { code: "PH", name: "Philippines", currency: "PHP", symbol: "₱", locale: "en-PH" },
  { code: "QA", name: "Qatar", currency: "QAR", symbol: "﷼", locale: "ar-QA" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", symbol: "﷼", locale: "ar-SA" },
  { code: "SG", name: "Singapore", currency: "SGD", symbol: "S$", locale: "en-SG" },
  { code: "KR", name: "South Korea", currency: "KRW", symbol: "₩", locale: "ko-KR" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", symbol: "Rs.", locale: "si-LK" },
  { code: "SY", name: "Syria", currency: "SYP", symbol: "£", locale: "ar-SY" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", symbol: "SM", locale: "tg-TJ" },
  { code: "TH", name: "Thailand", currency: "THB", symbol: "฿", locale: "th-TH" },
  { code: "TL", name: "Timor-Leste", currency: "USD", symbol: "$", locale: "pt-TL" },
  { code: "TR", name: "Turkey", currency: "TRY", symbol: "₺", locale: "tr-TR" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", symbol: "m", locale: "tk-TM" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", symbol: "د.إ", locale: "ar-AE" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", symbol: "soʻm", locale: "uz-UZ" },
  { code: "VN", name: "Vietnam", currency: "VND", symbol: "₫", locale: "vi-VN" },
  { code: "YE", name: "Yemen", currency: "YER", symbol: "﷼", locale: "ar-YE" },

  // Europe
  { code: "AL", name: "Albania", currency: "ALL", symbol: "L", locale: "sq-AL" },
  { code: "AD", name: "Andorra", currency: "EUR", symbol: "€", locale: "ca-AD" },
  { code: "AT", name: "Austria", currency: "EUR", symbol: "€", locale: "de-AT" },
  { code: "BY", name: "Belarus", currency: "BYN", symbol: "Br", locale: "be-BY" },
  { code: "BE", name: "Belgium", currency: "EUR", symbol: "€", locale: "nl-BE" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", symbol: "KM", locale: "bs-BA" },
  { code: "BG", name: "Bulgaria", currency: "BGN", symbol: "лв", locale: "bg-BG" },
  { code: "HR", name: "Croatia", currency: "EUR", symbol: "€", locale: "hr-HR" },
  { code: "CZ", name: "Czech Republic", currency: "CZK", symbol: "Kč", locale: "cs-CZ" },
  { code: "DK", name: "Denmark", currency: "DKK", symbol: "kr", locale: "da-DK" },
  { code: "EE", name: "Estonia", currency: "EUR", symbol: "€", locale: "et-EE" },
  { code: "FI", name: "Finland", currency: "EUR", symbol: "€", locale: "fi-FI" },
  { code: "FR", name: "France", currency: "EUR", symbol: "€", locale: "fr-FR" },
  { code: "DE", name: "Germany", currency: "EUR", symbol: "€", locale: "de-DE" },
  { code: "GR", name: "Greece", currency: "EUR", symbol: "€", locale: "el-GR" },
  { code: "HU", name: "Hungary", currency: "HUF", symbol: "Ft", locale: "hu-HU" },
  { code: "IS", name: "Iceland", currency: "ISK", symbol: "kr", locale: "is-IS" },
  { code: "IE", name: "Ireland", currency: "EUR", symbol: "€", locale: "en-IE" },
  { code: "IT", name: "Italy", currency: "EUR", symbol: "€", locale: "it-IT" },
  { code: "XK", name: "Kosovo", currency: "EUR", symbol: "€", locale: "sq-XK" },
  { code: "LV", name: "Latvia", currency: "EUR", symbol: "€", locale: "lv-LV" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", symbol: "Fr.", locale: "de-LI" },
  { code: "LT", name: "Lithuania", currency: "EUR", symbol: "€", locale: "lt-LT" },
  { code: "LU", name: "Luxembourg", currency: "EUR", symbol: "€", locale: "lb-LU" },
  { code: "MT", name: "Malta", currency: "EUR", symbol: "€", locale: "mt-MT" },
  { code: "MD", name: "Moldova", currency: "MDL", symbol: "L", locale: "ro-MD" },
  { code: "MC", name: "Monaco", currency: "EUR", symbol: "€", locale: "fr-MC" },
  { code: "ME", name: "Montenegro", currency: "EUR", symbol: "€", locale: "sr-ME" },
  { code: "NL", name: "Netherlands", currency: "EUR", symbol: "€", locale: "nl-NL" },
  { code: "MK", name: "North Macedonia", currency: "MKD", symbol: "ден", locale: "mk-MK" },
  { code: "NO", name: "Norway", currency: "NOK", symbol: "kr", locale: "nb-NO" },
  { code: "PL", name: "Poland", currency: "PLN", symbol: "zł", locale: "pl-PL" },
  { code: "PT", name: "Portugal", currency: "EUR", symbol: "€", locale: "pt-PT" },
  { code: "RO", name: "Romania", currency: "RON", symbol: "lei", locale: "ro-RO" },
  { code: "RU", name: "Russia", currency: "RUB", symbol: "₽", locale: "ru-RU" },
  { code: "SM", name: "San Marino", currency: "EUR", symbol: "€", locale: "it-SM" },
  { code: "RS", name: "Serbia", currency: "RSD", symbol: "дин.", locale: "sr-RS" },
  { code: "SK", name: "Slovakia", currency: "EUR", symbol: "€", locale: "sk-SK" },
  { code: "SI", name: "Slovenia", currency: "EUR", symbol: "€", locale: "sl-SI" },
  { code: "ES", name: "Spain", currency: "EUR", symbol: "€", locale: "es-ES" },
  { code: "SE", name: "Sweden", currency: "SEK", symbol: "kr", locale: "sv-SE" },
  { code: "CH", name: "Switzerland", currency: "CHF", symbol: "Fr.", locale: "de-CH" },
  { code: "UA", name: "Ukraine", currency: "UAH", symbol: "₴", locale: "uk-UA" },
  { code: "GB", name: "United Kingdom", currency: "GBP", symbol: "£", locale: "en-GB" },
  { code: "VA", name: "Vatican City", currency: "EUR", symbol: "€", locale: "it-VA" },

  // North America
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD", symbol: "$", locale: "en-AG" },
  { code: "BS", name: "Bahamas", currency: "BSD", symbol: "$", locale: "en-BS" },
  { code: "BB", name: "Barbados", currency: "BBD", symbol: "$", locale: "en-BB" },
  { code: "BZ", name: "Belize", currency: "BZD", symbol: "BZ$", locale: "en-BZ" },
  { code: "CA", name: "Canada", currency: "CAD", symbol: "C$", locale: "en-CA" },
  { code: "CR", name: "Costa Rica", currency: "CRC", symbol: "₡", locale: "es-CR" },
  { code: "CU", name: "Cuba", currency: "CUP", symbol: "$", locale: "es-CU" },
  { code: "DM", name: "Dominica", currency: "XCD", symbol: "$", locale: "en-DM" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", symbol: "RD$", locale: "es-DO" },
  { code: "SV", name: "El Salvador", currency: "USD", symbol: "$", locale: "es-SV" },
  { code: "GD", name: "Grenada", currency: "XCD", symbol: "$", locale: "en-GD" },
  { code: "GT", name: "Guatemala", currency: "GTQ", symbol: "Q", locale: "es-GT" },
  { code: "HT", name: "Haiti", currency: "HTG", symbol: "G", locale: "fr-HT" },
  { code: "HN", name: "Honduras", currency: "HNL", symbol: "L", locale: "es-HN" },
  { code: "JM", name: "Jamaica", currency: "JMD", symbol: "J$", locale: "en-JM" },
  { code: "MX", name: "Mexico", currency: "MXN", symbol: "Mex$", locale: "es-MX" },
  { code: "NI", name: "Nicaragua", currency: "NIO", symbol: "C$", locale: "es-NI" },
  { code: "PA", name: "Panama", currency: "PAB", symbol: "B/.", locale: "es-PA" },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD", symbol: "$", locale: "en-KN" },
  { code: "LC", name: "Saint Lucia", currency: "XCD", symbol: "$", locale: "en-LC" },
  { code: "VC", name: "Saint Vincent and the Grenadines", currency: "XCD", symbol: "$", locale: "en-VC" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", symbol: "TT$", locale: "en-TT" },
  { code: "US", name: "United States", currency: "USD", symbol: "$", locale: "en-US" },

  // South America
  { code: "AR", name: "Argentina", currency: "ARS", symbol: "AR$", locale: "es-AR" },
  { code: "BO", name: "Bolivia", currency: "BOB", symbol: "Bs.", locale: "es-BO" },
  { code: "BR", name: "Brazil", currency: "BRL", symbol: "R$", locale: "pt-BR" },
  { code: "CL", name: "Chile", currency: "CLP", symbol: "$", locale: "es-CL" },
  { code: "CO", name: "Colombia", currency: "COP", symbol: "$", locale: "es-CO" },
  { code: "EC", name: "Ecuador", currency: "USD", symbol: "$", locale: "es-EC" },
  { code: "GY", name: "Guyana", currency: "GYD", symbol: "G$", locale: "en-GY" },
  { code: "PY", name: "Paraguay", currency: "PYG", symbol: "₲", locale: "es-PY" },
  { code: "PE", name: "Peru", currency: "PEN", symbol: "S/", locale: "es-PE" },
  { code: "SR", name: "Suriname", currency: "SRD", symbol: "$", locale: "nl-SR" },
  { code: "UY", name: "Uruguay", currency: "UYU", symbol: "$U", locale: "es-UY" },
  { code: "VE", name: "Venezuela", currency: "VES", symbol: "Bs.", locale: "es-VE" },

  // Africa
  { code: "DZ", name: "Algeria", currency: "DZD", symbol: "دج", locale: "ar-DZ" },
  { code: "AO", name: "Angola", currency: "AOA", symbol: "Kz", locale: "pt-AO" },
  { code: "BJ", name: "Benin", currency: "XOF", symbol: "CFA", locale: "fr-BJ" },
  { code: "BW", name: "Botswana", currency: "BWP", symbol: "P", locale: "en-BW" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", symbol: "CFA", locale: "fr-BF" },
  { code: "BI", name: "Burundi", currency: "BIF", symbol: "FBu", locale: "fr-BI" },
  { code: "CV", name: "Cape Verde", currency: "CVE", symbol: "$", locale: "pt-CV" },
  { code: "CM", name: "Cameroon", currency: "XAF", symbol: "FCFA", locale: "fr-CM" },
  { code: "CF", name: "Central African Republic", currency: "XAF", symbol: "FCFA", locale: "fr-CF" },
  { code: "TD", name: "Chad", currency: "XAF", symbol: "FCFA", locale: "fr-TD" },
  { code: "KM", name: "Comoros", currency: "KMF", symbol: "CF", locale: "ar-KM" },
  { code: "CD", name: "Democratic Republic of the Congo", currency: "CDF", symbol: "FC", locale: "fr-CD" },
  { code: "CG", name: "Republic of the Congo", currency: "XAF", symbol: "FCFA", locale: "fr-CG" },
  { code: "CI", name: "Côte d'Ivoire", currency: "XOF", symbol: "CFA", locale: "fr-CI" },
  { code: "DJ", name: "Djibouti", currency: "DJF", symbol: "Fdj", locale: "fr-DJ" },
  { code: "EG", name: "Egypt", currency: "EGP", symbol: "E£", locale: "ar-EG" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", symbol: "FCFA", locale: "es-GQ" },
  { code: "ER", name: "Eritrea", currency: "ERN", symbol: "Nfk", locale: "ti-ER" },
  { code: "SZ", name: "Eswatini", currency: "SZL", symbol: "E", locale: "en-SZ" },
  { code: "ET", name: "Ethiopia", currency: "ETB", symbol: "Br", locale: "am-ET" },
  { code: "GA", name: "Gabon", currency: "XAF", symbol: "FCFA", locale: "fr-GA" },
  { code: "GM", name: "Gambia", currency: "GMD", symbol: "D", locale: "en-GM" },
  { code: "GH", name: "Ghana", currency: "GHS", symbol: "₵", locale: "en-GH" },
  { code: "GN", name: "Guinea", currency: "GNF", symbol: "FG", locale: "fr-GN" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", symbol: "CFA", locale: "pt-GW" },
  { code: "KE", name: "Kenya", currency: "KES", symbol: "KSh", locale: "en-KE" },
  { code: "LS", name: "Lesotho", currency: "LSL", symbol: "L", locale: "en-LS" },
  { code: "LR", name: "Liberia", currency: "LRD", symbol: "L$", locale: "en-LR" },
  { code: "LY", name: "Libya", currency: "LYD", symbol: "ل.د", locale: "ar-LY" },
  { code: "MG", name: "Madagascar", currency: "MGA", symbol: "Ar", locale: "mg-MG" },
  { code: "MW", name: "Malawi", currency: "MWK", symbol: "MK", locale: "en-MW" },
  { code: "ML", name: "Mali", currency: "XOF", symbol: "CFA", locale: "fr-ML" },
  { code: "MR", name: "Mauritania", currency: "MRU", symbol: "UM", locale: "ar-MR" },
  { code: "MU", name: "Mauritius", currency: "MUR", symbol: "₨", locale: "en-MU" },
  { code: "MA", name: "Morocco", currency: "MAD", symbol: "د.م.", locale: "ar-MA" },
  { code: "MZ", name: "Mozambique", currency: "MZN", symbol: "MT", locale: "pt-MZ" },
  { code: "NA", name: "Namibia", currency: "NAD", symbol: "N$", locale: "en-NA" },
  { code: "NE", name: "Niger", currency: "XOF", symbol: "CFA", locale: "fr-NE" },
  { code: "NG", name: "Nigeria", currency: "NGN", symbol: "₦", locale: "en-NG" },
  { code: "RW", name: "Rwanda", currency: "RWF", symbol: "FRw", locale: "rw-RW" },
  { code: "ST", name: "São Tomé and Príncipe", currency: "STN", symbol: "Db", locale: "pt-ST" },
  { code: "SN", name: "Senegal", currency: "XOF", symbol: "CFA", locale: "fr-SN" },
  { code: "SC", name: "Seychelles", currency: "SCR", symbol: "₨", locale: "en-SC" },
  { code: "SL", name: "Sierra Leone", currency: "SLE", symbol: "Le", locale: "en-SL" },
  { code: "SO", name: "Somalia", currency: "SOS", symbol: "Sh", locale: "so-SO" },
  { code: "ZA", name: "South Africa", currency: "ZAR", symbol: "R", locale: "en-ZA" },
  { code: "SS", name: "South Sudan", currency: "SSP", symbol: "£", locale: "en-SS" },
  { code: "SD", name: "Sudan", currency: "SDG", symbol: "ج.س.", locale: "ar-SD" },
  { code: "TZ", name: "Tanzania", currency: "TZS", symbol: "TSh", locale: "sw-TZ" },
  { code: "TG", name: "Togo", currency: "XOF", symbol: "CFA", locale: "fr-TG" },
  { code: "TN", name: "Tunisia", currency: "TND", symbol: "د.ت", locale: "ar-TN" },
  { code: "UG", name: "Uganda", currency: "UGX", symbol: "USh", locale: "en-UG" },
  { code: "ZM", name: "Zambia", currency: "ZMW", symbol: "ZK", locale: "en-ZM" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWG", symbol: "ZiG", locale: "en-ZW" },

  // Oceania
  { code: "AU", name: "Australia", currency: "AUD", symbol: "A$", locale: "en-AU" },
  { code: "FJ", name: "Fiji", currency: "FJD", symbol: "FJ$", locale: "en-FJ" },
  { code: "KI", name: "Kiribati", currency: "AUD", symbol: "A$", locale: "en-KI" },
  { code: "MH", name: "Marshall Islands", currency: "USD", symbol: "$", locale: "en-MH" },
  { code: "FM", name: "Micronesia", currency: "USD", symbol: "$", locale: "en-FM" },
  { code: "NR", name: "Nauru", currency: "AUD", symbol: "A$", locale: "en-NR" },
  { code: "NZ", name: "New Zealand", currency: "NZD", symbol: "NZ$", locale: "en-NZ" },
  { code: "PW", name: "Palau", currency: "USD", symbol: "$", locale: "en-PW" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", symbol: "K", locale: "en-PG" },
  { code: "WS", name: "Samoa", currency: "WST", symbol: "T", locale: "en-WS" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", symbol: "SI$", locale: "en-SB" },
  { code: "TO", name: "Tonga", currency: "TOP", symbol: "T$", locale: "to-TO" },
  { code: "TV", name: "Tuvalu", currency: "AUD", symbol: "A$", locale: "en-TV" },
  { code: "VU", name: "Vanuatu", currency: "VUV", symbol: "VT", locale: "bi-VU" },
];

export const DEFAULT_COUNTRY = COUNTRIES.find(
    (country) => country.code === "NP"
)!;